# Generated by Django 4.2 on 2023-04-18 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('search_id', models.UUIDField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('file_mask', models.CharField(max_length=255)),
                ('size_value', models.IntegerField()),
                ('size_operator', models.CharField(max_length=2)),
                ('creation_time_value', models.DateTimeField()),
                ('creation_time_operator', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.search')),
            ],
        ),
    ]
