# Generated by Django 4.2 on 2023-04-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='paths',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='search',
            name='creation_time_operator',
            field=models.CharField(choices=[('eq', 'Eq'), ('gt', 'Gr'), ('lt', 'Lt'), ('ge', 'Ge'), ('le', 'Le')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='creation_time_value',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='file_mask',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='size_operator',
            field=models.CharField(choices=[('eq', 'Eq'), ('gt', 'Gr'), ('lt', 'Lt'), ('ge', 'Ge'), ('le', 'Le')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='size_value',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='text',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='SearchResult',
        ),
    ]
