# Generated by Django 4.2 on 2023-04-19 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_alter_search_creation_time_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='creation_time_operator',
        ),
        migrations.RemoveField(
            model_name='search',
            name='creation_time_value',
        ),
        migrations.RemoveField(
            model_name='search',
            name='file_mask',
        ),
        migrations.RemoveField(
            model_name='search',
            name='size_operator',
        ),
        migrations.RemoveField(
            model_name='search',
            name='size_value',
        ),
        migrations.RemoveField(
            model_name='search',
            name='text',
        ),
    ]
