# Generated by Django 4.2 on 2023-04-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_remove_search_creation_time_operator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='paths',
            field=models.TextField(),
        ),
    ]
